tenant: ac360 # Enter your tenant name here
app: enterprise # Enter your application name here
service: demo-lead-capture

frameworkVersion: '>=1.38.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs6.10

functions:
  formSubmit:
    handler: index.submit
    events:
      - http:
          path: submit
          method: post
          cors: true

custom:
  client:
    bucketName: sfe-demo-lead-capture # Change this to a universally unique AWS S3 bucket name
    distributionFolder: ../frontend/build

plugins:
  - '@serverless/enterprise-plugin'
  - serverless-finch
